<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alyssa Back, Catherine Cho, Iris Ta">
<meta name="dcterms.date" content="2026-04-18">

<title>Understanding Spotify User Behavior Across Different Factors</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="36315FinalProject_files/libs/clipboard/clipboard.min.js"></script>
<script src="36315FinalProject_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="36315FinalProject_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="36315FinalProject_files/libs/quarto-html/popper.min.js"></script>
<script src="36315FinalProject_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="36315FinalProject_files/libs/quarto-html/anchor.min.js"></script>
<link href="36315FinalProject_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="36315FinalProject_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="36315FinalProject_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="36315FinalProject_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="36315FinalProject_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Understanding Spotify User Behavior Across Different Factors</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Alyssa Back, Catherine Cho, Iris Ta </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="motivation" class="level1">
<h1>Motivation:</h1>
<p>Spotify is a global music streaming platform that enables users to create playlists, discover new songs, and receive personalized recommendations based on their listening behavior. With a large and diverse user base, understanding how users interact with the platform is important for improving user experience and increasing long-term retention.</p>
<p>This project investigates how user behavior, advertising interactions, and user profiles relate to engagement, satisfaction, and subscription retention on Spotify. In particular, we analyze how listening behavior, ad-related activity, and user characteristics influence subscription status and music recommendation ratings.</p>
<p>Our analysis shows that basic engagement metrics such as listening hours and skip rates do not strongly differentiate between active and inactive users. Similarly, advertisement interactions and ad-to-subscription conversions show little to no meaningful association with long-term retention or engagement levels. Finally, music recommendation ratings remain consistently high across user profiles defined by subscription type and genre, with minimal variation in average ratings or in the likelihood of giving high ratings.</p>
<p>Overall, these findings suggest that no single behavioral or demographic factor strongly explains user retention or satisfaction in this dataset. Instead, user engagement patterns appear relatively uniform across groups, indicating that retention is likely influenced by a more complex combination of factors than those captured in this analysis. This highlights the need for more nuanced modeling approaches when studying user behavior on music streaming platforms.</p>
</section>
<section id="dataset-overview" class="level1">
<h1>Dataset Overview:</h1>
<p>We obtained our dataset through Kaggle: https://www.kaggle.com/datasets/sahilislam007/spotify-user-behavior-and-pattern</p>
<p>This analysis draws from a synthetic dataset of 50,000 observations. Each row represents a Spotify user across 18 variables spanning demographics, subscription behavior, and advertisement interactions, to help us investigate factors that shape long term user engagement and retention.</p>
<p>Although the dataset is synthetically generated, it is designed to reflect the patterns of Spotify users in real life.</p>
<p><strong>User_id:</strong> Unique identifier assigned to each user in the dataset.</p>
<p><strong>Country:</strong> Country where the user is located.</p>
<p><strong>Age:</strong> Age of the user.</p>
<p><strong>Signup_date:</strong> The date when the user signed up for the platform.</p>
<p><strong>Subscription_type:</strong> Type of subscription used by the user. Examples may include: Free Premium Family Student</p>
<p><strong>Subscription_status:</strong> Indicates whether the user currently has an active or inactive subscription.</p>
<p><strong>Months_inactive:</strong> Number of months the user has been inactive on the platform.</p>
<p><strong>Inactive_3_months_flag:</strong> Binary indicator showing whether the user has been inactive for 3 months or more. 1 = Inactive for 3+ months 0</p>
<p><strong>Ad_interaction:</strong> Indicates whether the user has interacted with advertisements on the platform.</p>
<p><strong>Ad_conversion_to_subscription:</strong> Indicates whether an advertisement resulted in the user converting to a paid subscription.</p>
<p><strong>Music_suggestion_rating_1_to_5:</strong> User rating (1–5 scale) for the platform’s music recommendation system. 1 = Very poor recommendations 5 = Excellent recommendations</p>
<p><strong>Avg_listening_hours_per_week:</strong> Average number of hours the user spends listening to music per week.</p>
<p><strong>Favorite_genre:</strong> The music genre most frequently listened to by the user. Examples may include: Pop Rock Hip-Hop Electronic Jazz Classical</p>
<p><strong>Most_liked_feature:</strong> The feature that the user likes the most on the platform. Examples: Personalized playlists Discover weekly Offline downloads Podcasts Social sharing</p>
<p><strong>Desired_future_feature:</strong> Feature the user would like to see added or improved in the future.</p>
<p><strong>Primary_device:</strong> Main device used to access the music platform. Examples: Mobile Desktop Tablet Smart Speaker</p>
<p><strong>Playlists_created:</strong> Number of playlists created by the user.</p>
<p><strong>Avg_skips_per_day:</strong> Average number of songs skipped by the user per day. Higher values may indicate: Low engagement with recommendations Exploration behavior</p>
<p>Prior to any analysis, we checked the data to see if there were any missing values. Since it is synthetic data, we did not find any. We did transform some variables to do various types of graphs.</p>
</section>
<section id="research-questions" class="level1">
<h1>Research Questions:</h1>
<p>Our three research questions are as follows:</p>
<ol type="1">
<li>What behavioral patterns (such as skips and listening hours) predict subscription cancellation, and what do these patterns reveal about user disengagement?</li>
</ol>
<p>Understanding these behaviors is important because identifying early signs of disengagement can help Spotify intervene before users cancel their subscriptions, improving retention.</p>
<ol start="2" type="1">
<li>Does ad interaction correlate with long-term activity, and how effective are ads in maintaining user engagement?</li>
</ol>
<p>This question matters because ads are a key revenue stream for Spotify, and understanding their impact on retention can inform more effective advertising strategies.</p>
<ol start="3" type="1">
<li>What user profiles (subscription type and preferred genre) are associated with differences in music recommendation ratings?</li>
</ol>
<p>This is important because identifying which users receive the most accurate recommendations can help improve Spotify’s recommendation algorithms and personalize the user experience.</p>
<p>Together, these questions explore how behavioral patterns, advertising interactions, and user characteristics influence engagement and satisfaction on the platform. By examining these relationships, we aim to identify key drivers of user retention and recommendation quality, providing insights that can guide improvements to Spotify’s features and overall user experience.</p>
</section>
<section id="question-1-what-behavioral-patterns-such-as-skips-and-listening-hours-predict-subscription-cancellation-and-what-do-these-patterns-reveal-about-user-disengagement" class="level1">
<h1>Question 1: What behavioral patterns (such as skips and listening hours) predict subscription cancellation, and what do these patterns reveal about user disengagement?</h1>
<p>To answer Research Question 1, we examine how listening time differs between users who remain subscribed and those who cancel their subscription. Since listening time reflects overall platform engagement, comparing its distribution across these groups provide insight into whether engagement intensity is associated with user retention.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="36315FinalProject_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The boxplot shows that the distribution of average listening hours per week is very similar between active and inactive users. The medians are close, and the interquartile ranges overlap significantly, indicating little difference in listening behavior between the two groups.</p>
<p>This suggests that listening time alone is not a strong indicator of whether a user will cancel their subscription, and that other factors likely play a more important role in predicting user retention.</p>
<p>To further address Research Question 1, we examine another key behavioral metric: the average number of skips per day. Skipping behavior reflects user satisfaction and content relevance, as higher skip rates may indicate that recommended tracks are not aligning with user preferences.</p>
<p>We visualize this relationship using a histogram of average skips per day grouped by subscription status. This plot highlights differences in central tendency, variability, and extreme values, allowing for a direct comparison of engagement patterns between active and inactive users.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="36315FinalProject_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the distribution of average skips per day, we observe that both active and inactive users exhibit very similar patterns. In both groups, the data is centered around approximately 10–12 skips per day, with relatively symmetric distributions and no strong evidence of skewness. While active users show a slightly wider spread and a few higher-end outliers, these differences are minor and do not substantially distinguish the two groups.</p>
<p>This suggests that skip behavior, like listening time, is not a strong standalone predictor of subscription cancellation. Despite being an intuitive measure of dissatisfaction, skip rates do not differ meaningfully between retained and churned users.</p>
<p>Taken together with the previous analysis on listening hours, these results indicate that basic engagement metrics alone are insufficient to explain user churn. Instead, subscription decisions are likely influenced by a more complex combination of factors, such as user preferences, platform experience, and external considerations.</p>
</section>
<section id="question-2-does-ad-interaction-correlate-with-long-term-activity-and-how-effective-are-ads-in-maintaining-user-engagement" class="level1">
<h1>Question 2: Does ad interaction correlate with long-term activity, and how effective are ads in maintaining user engagement?</h1>
<p>To address Research Question 2, we examine whether user interaction with advertisements is associated with long-term retention, measured by months of inactivity. If advertisements are effective in maintaining engagement, we would expect users who interact with ads to exhibit lower inactivity levels. We look at this relationship throuhg a violin plot.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="36315FinalProject_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The distribution of inactivity months for users who interacted with advertisements and those who did not shows nearly identical patterns. Both groups display a heavily right-skewed distribution, with most users concentrated between zero and two months of inactivity and a small number of outliers extending to higher values. The median inactivity for both groups is approximately one month, indicating no meaningful difference in central tendency.</p>
<p>This suggests that ad interaction is not strongly associated with improved long-term retention. Despite the expectation that engaging with advertisements might reflect higher user involvement, the data indicates that users who interact with ads do not remain active significantly longer than those who do not.</p>
<p>Overall, these findings imply that while Spotify’s advertisements may successfully capture user attention, they do not translate into sustained engagement. This highlights a potential limitation in the effectiveness of current advertising strategies and suggests that improvements in ad relevance or targeting may be necessary to meaningfully impact user retention. This aligns with earlier findings that basic engagement metrics alone do not strongly predict retention.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  avg_listening_hours_per_week by ad_conversion_to_subscription
t = 0.26824, df = 5207.7, p-value = 0.7885
alternative hypothesis: true difference in means between group No and group Yes is not equal to 0
95 percent confidence interval:
 -0.1069444  0.1408496
sample estimates:
 mean in group No mean in group Yes 
         9.990461          9.973509 </code></pre>
</div>
</div>
<p>To formally test whether ad conversion influences engagement, we use a Welch two-sample t-test comparing average weekly listening hours between users who converted to a paid subscription through an advertisement and those who did not. A Welch t-test is appropriate here because we are comparing means across two independent groups and do not assume equal variance between them.</p>
<p>The results show no statistically significant difference (t = 0.268, df = 5207.7, p = 0.789). Because the p-value far exceeds our significance threshold of 0.05 — the conventional cutoff below which we would consider a result unlikely to be due to chance alone — we fail to reject the null hypothesis that the two group means are equal. In practical terms, users who subscribed through an ad listened to an average of 9.97 hours per week, compared to 9.99 hours for those who did not — a difference of less than two minutes. The 95% confidence interval for this difference (-0.107, 0.141) includes zero, further confirming that any difference is negligible.</p>
<p>To further address Research Question 2, we examine whether converting through a Spotify advertisement is associated with long-term retention by comparing the proportion of active and inactive users across conversion groups through a bar chart.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="36315FinalProject_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The stacked bar chart shows that both groups—users who converted through an advertisement and those who did not—have nearly identical proportions, with approximately 80% active users and 20% inactive users in each group. This indicates that subscription status is largely independent of whether a user converted via an ad.</p>
<p>This suggests that ad conversion does not meaningfully improve long-term retention. Users who subscribe through advertisements are no more likely to remain active than those who subscribe through other means, indicating that ad-driven conversions do not produce more engaged users.</p>
<p>Overall, this finding reinforces earlier results that advertisement-related interactions have limited impact on sustained user engagement. While ads may be effective in acquiring new subscribers, they do not appear to influence whether those users remain active over time.</p>
</section>
<section id="question-3-what-user-profiles-subscription-type-and-preferred-genre-are-associated-with-differences-in-music-recommendation-ratings" class="level1">
<h1>Question 3: What user profiles (subscription type and preferred genre) are associated with differences in music recommendation ratings?</h1>
<p>To investigate whether certain user profiles are associated with differences in music recommendation ratings, we examine how average ratings vary across combinations of subscription type and favorite genre.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="36315FinalProject_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The heatmap shows that average recommendation ratings are highly consistent across all combinations of subscription type and favorite genre, with values generally clustered around 3.6–3.7. While there are minor fluctuations between groups, no genre or subscription category stands out as consistently receiving higher or lower ratings.</p>
<p>Overall, these results suggest that perceived recommendation quality is relatively stable across user profiles. This indicates that neither subscription type nor genre preference is a strong differentiator of user satisfaction in this dataset.</p>
<p>To further examine whether certain user groups are more likely to give high ratings (defined as 4 or above), we construct a mosaic plot comparing subscription type and rating category.</p>
<div class="cell" data-messages="false" data-warnings="false">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="36315FinalProject_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The mosaic plot shows little deviation from expected counts under independence, and the absence of strong Pearson residual shading suggests no evidence of an association between subscription type and rating category.</p>
<p>Taken together with the heatmap results, this indicates that music recommendation ratings remain relatively uniform across user profiles, with no strong evidence that subscription type or genre significantly influences perceived recommendation quality.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This study explored three dimensions of Spotify user behavior: the behavioral patterns that predict subscription cancellation, the relationship between advertising and long-term retention, and the user profiles associated with the highest music suggestion ratings.</p>
<p>Taken together, our three analyses paint a consistent picture: no single behavioral or demographic factor strongly explains user retention or satisfaction in this dataset.</p>
<p>For Research Question 1, both listening hours and skip rates were nearly identical between active and inactive users, suggesting that the platform engagement signals most readily available to Spotify do not reliably distinguish users who are about to churn from those who will stay. This is a meaningful finding — it implies that a simple threshold rule like “flag users who skip a lot” would not be an effective retention strategy.</p>
<p>For Research Question 2, neither ad interaction nor ad-driven subscription conversion was associated with measurable differences in long-term activity. Users who clicked on ads and converted were no more active — and listened to no more music — than users who found the platform through other means. This suggests that Spotify’s advertising may be reaching users who would have engaged at similar levels regardless, rather than selectively attracting high-engagement users.</p>
<p>For Research Question 3, music recommendation ratings clustered tightly between 3.6 and 3.7 across every combination of subscription type and favorite genre. Neither the mosaic plot nor the heatmap revealed any meaningful variation, indicating that perceived recommendation quality is uniform across user profiles rather than benefiting or disadvantaging particular groups.</p>
<p>Collectively, these findings suggest that retention and satisfaction on Spotify are shaped by a more complex combination of factors than basic behavioral metrics or demographic groupings can capture on their own. Because our dataset is synthetic, some of this uniformity may reflect the data generation process rather than true user behavior, and results should be interpreted with that limitation in mind.</p>
</section>
<section id="future-work" class="level1">
<h1>Future Work</h1>
<p>Several important questions remain that could not be addressed within the scope of this project.</p>
<p>First, while we examined listening hours and skip rates as standalone predictors of churn, we did not explore how these behaviors change over time for individual users. Sequential patterns — such as a gradual decline in listening hours over several weeks — may be far more predictive of cancellation than any single snapshot. Answering this would require time-series data and methods such as survival analysis or recurrent neural networks, which are beyond what was covered in this course.</p>
<p>Second, our treatment of advertising was necessarily simplified. We could only observe whether a user interacted with an ad and whether they converted — not the type of ad, its frequency, its timing relative to signup, or whether users were exposed but did not click. A more rigorous causal analysis of ad effectiveness would require either randomized experiment data or an instrumental variable approach to address the selection problem, neither of which is feasible with this dataset.</p>
<p>Third, and most importantly, all of our findings are drawn from a synthetic dataset designed to mimic Spotify user behavior. Real user data would contain more noise, more extreme outliers, and more genuine variation between groups. Future work using a real dataset — even an anonymized sample — would allow for more robust and generalizable conclusions. It would also make it possible to validate whether the uniform patterns observed here reflect true user behavior or are an artifact of how the synthetic data was generated.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>